### ISSUE TITLE
Internal server error when using resource documents/search

### ISSUE THREAD

**Issue by devbar** [amagno-io/amagno-web-api-postman#1]
My scenario is to search a document by Text SLKD1003. After sending the request with json in body, the server respons 500, internal server error.

```
{
	"searchText": "SLKD1003",
	"vaultIds": [
		"bcb7443a-23e4-e911-b5b2-00155d1e0f20"
		],
	"sortInformation": {
		"tagDefinitionId": "79c9eb34-711c-4120-8d67-7045f551c4f3",
		"order": "Ascending"
	}
}
```

The eventlog sends this message.

> ExceptionType: AmagnoServerException
> Message: Error searching content simply
> Stack trace: 
> 		Amagno.BaseDB.AmagnoServerException.Log(System.Exception exception, System.String message, System.Diagnostics.EventLogEntryType eventType)
> 		Amagno.Base.AmagnoDB.SearchContentSimple(Autofac.ILifetimeScope lifetimeScope, Amagno.ExternalServiceContracts.SearchContentSimpleArg arg)
> 		Amagno.AmagnoService.AmagnoService.SearchContentSimple(Amagno.ExternalServiceContracts.SearchContentSimpleArg arg)
> 
> 	ExceptionType: ArgumentNullException
> 	Message: Der Wert darf nicht NULL sein.
> Parametername: value
> 	ParamName: value
> 	Stack trace: 
> 		   bei Amagno.ExternalServiceContracts.SelectionValueNode..ctor(Guid id, String value, Boolean active)
>    bei Amagno.Base.SimpleSearchConditionService.<>c.<RetrieveCondition>b__4_0(AmagnoUser user)
>    bei System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
>    bei System.Linq.Buffer`1..ctor(IEnumerable`1 source)
>    bei System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
>    bei Amagno.Base.SimpleSearchConditionService.RetrieveCondition(String searchString, Guid[] groupIds, Guid callingUserId)
>    bei Amagno.Base.AmagnoDB.SearchContentSimple(ILifetimeScope lifetimeScope, SearchContentSimpleArg arg)

**Amagno: 5.5.8**

**Comment by gerrit-amagno** [comment]
It works with the business cloud.

`curl -X POST \
  https://amagno.me/api/v2/documents/search \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Authorization: Bearer TOKEN' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 209' \
  -H 'Content-Type: application/json' \
  -H 'Host: amagno.me' \
  -H 'Postman-Token: b386e42f-b6d4-4dec-ac82-d42a0cb9eb1f,83369558-a3fe-4792-9130-23d088579e2b' \
  -H 'User-Agent: PostmanRuntime/7.17.1' \
  -H 'cache-control: no-cache' \
  -d '{
	"searchText": "SLKD1003",
	"vaultIds": [
		"bcb7443a-23e4-e911-b5b2-00155d1e0f20"
		],
	"sortInformation": {
		"tagDefinitionId": "79c9eb34-711c-4120-8d67-7045f551c4f3",
		"order": "Ascending"
	}
}'`

The event log message indicates a bug. I will close this issue and contact you to get further information. The error is not the postman project.
